### ISSUE TITLE
Feature: proceed with other quests for the same object

### ISSUE THREAD

**Issue by NotSoImportant** [Helium314/StreetComplete#369]
Hi @Helium314 and @mnalis I really much like the changes done in your fork. Here is another improvement:

**Use case**
Less clicks - more focused experiance

**Proposed Solution**
When there are multiple quests per object you are already showing them in the left. 
Now when clicking "ok" to answer one and there are still some left, directly open the (any) next quest for this object.

**Comment by Helium314** [comment]
I had already thought about this, but it is not so simple.
There are a lot of things happening in background after solving a quest, like persisting changes and generating new available quests, and sometimes previously available quests may disappear if you use specific quest settings.

If you have a slow phone, you may notice that sometimes it takes a while for the next quest to appear. This delay would also be there before the next quest for the same object is shown.

**Comment by mnalis** [comment]
I agree that it is problematic. Also, I do not think I personally would enable this feature in most cases even if available, as my flow usually concentrates on solving same type quest for other items before switching. 

E.g. I usually **do** things in following order:

- solve `1st building type`, `2nd building type`, `3rd building type`, `1st housenumber`, `2nd housenumber`, `3rd housenumber`, `1st streetaddr`, `2nd streetaddr`, `3rd streetaddr`, `1st building number or levels`, `2nd building number or levels`, `3rd building number or levels`... and **not**:
- solve `1st building type`, `1st housenumber`, `1st streetaddr`, `1st building number or levels`, `2nd building type`, `2nd housenumber`, `2nd streetaddr`, `2nd building number or levels`, `3rd building type`, `3rd housenumber`, `3rd streetaddr`, `3rd building number or levels`... - as that introduces too much context switching and even on very fast phone would actually  slow me down considerably. _And_ also I often only have time for **some** of quests, and prefer to solve high-priority ones like addresses, instead of wasting time on less-important building levels, roof types etc. 

I _might_ like it if it were limited to specific, highly isolated (e.g. unlikely to be more than one present on the map) quests (like `steps`), but definitely not for anything `building`/`crossing`/`amenity` related, but that would require having it be even more complex and less intuitive, and thus likely making it even less desirable.

See however related upstream https://github.com/streetcomplete/StreetComplete/issues/124#issuecomment-890463682 and linked issues and comments for some ideas on that feature, for people who might like that (or at least who think they would :smile:).

**Comment by Helium314** [comment]
With the changes done as part of adding overlays, implementing this should actually be rather simple.
