### ISSUE TITLE
Crash when measuring road width

### ISSUE THREAD

**Issue by Helium314** [Helium314/StreetComplete#397]
Got a bug report for 47.0_ee
```
Describe how to reproduce it here:

Measure road width using the camera

Thread: ImageStreamHandler
App version: 47.0_ee
Device: Sony XQ-CC54, Android 12
Locale: de_DE
Stack trace:
java.lang.IllegalStateException: maxImages (16) has already been acquired, call #close before acquiring more.
at android.media.ImageReader.acquireNextImage(ImageReader.java:560)
at android.media.ImageReader.acquireLatestImage(ImageReader.java:441)
at dcy.onImageAvailable(PG:10)
at android.media.ImageReader$1.run(ImageReader.java:836)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:346)
at android.os.Looper.loop(Looper.java:475)
at android.os.HandlerThread.run(HandlerThread.java:67)
```

I have no idea what is going on, as I don't have Play Services and thus never tried AR measurements. No SC code in the crash report doesn't help...
Apparently one can take photos in AR mode, and maybe after taking 16 photos it crashes? Can anyone test this?

**Comment by HolgerJeromin** [comment]
I tested this and have problems with it. 
v48.0-beta1_ee on android 10

First test worked like a charm. Tested > 20 measurements

But all later tests kind of "worked", but did not show an image:
Live image from camera: black
Surface arrow: no/black
measurement line: no/black
measured distance bubble: yes
So I get the left instead of the right:
![image](https://user-images.githubusercontent.com/2410353/196364440-b8ea5fd1-ecf0-44b6-aec6-bd74d8275b17.png)



Killing app did not recovered the image.

**Comment by HolgerJeromin** [comment]
Sorry, should have added this. 
StreetComplete was working as expected even after EE has gone "black".

Now the ee has recovered (used the phone with some apps) and I am not able to break it again. :-(
Not very helpful...

**Comment by Helium314** [comment]
Well, looks like all I can do for now is hope that it doesn't get worse...
I didn't touch any related code, but the difference you showed is pretty obvious.

**Comment by mnalis** [comment]
BTW camera going black is come cases after using AR seems to happen in upstream too: https://github.com/streetcomplete/StreetComplete/issues/4611

**Comment by Helium314** [comment]
ARCore is now removed, so this is not an issue any more. At least not for SC_EE.
