### ISSUE TITLE
New Quest: Can a water bottle be filled here?

### ISSUE THREAD

**Issue by mcliquid** [Helium314/StreetComplete#510]
### General
Affected tag(s) to be modified/added: [bottle](https://wiki.openstreetmap.org/wiki/Key:bottle)
Question asked: **Can a water bottle be filled here?**

See also rejected SC quest: https://github.com/streetcomplete/StreetComplete/issues/4110

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md)):
- [ ] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give should have an equivalent tagging (SCEE quests may not be answerable in all cases, but please keep this rare)
- [x] 🐿️ A survey is necessary (may require knowledge of the subject, though easy answering for everyone is preferred)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

```
nodes, ways with
          (amenit~drinking_water|water_point or man_made~water_tap|drinking_fountain)
          and access !~ no|private
          and !bottle
```

**Proposed UI:**

* Recycle the AddWheelchairAccess quest & UI
* Simple "Yes, No and Limited" answers

Another option would be an Image Selection. I could prepare three images which shows a 1 liter bottle (classic bicycle bottle) in the three situations.

**Comment by Helium314** [comment]
Yes / no / limited would be fine, if there is some description what limited means.

**Comment by mnalis** [comment]
While I love microtagging water sources, I'm not particularly fond of `bottle` tag as it is very poorly and unclearly defined (see the wiki and SC discussion), and so different people have conflicting ideas what `yes` and `no` actually mean... 

But if it is going to be written anyway, I'd advise to at least also **add `Designated for bottles only` answer** (to retag as clearly defined [fountain=bottle_refill](https://wiki.openstreetmap.org/wiki/Tag:fountain%3Dbottle_refill) - which is probably what huge number of those `bottle=yes` actually was intended to mean - as I have rarely if ever found water source that cannot be used to fill bottle if one is persistent enough)

**Comment by mnalis** [comment]
> Do you think it would make sense to follow up the definition with a proposal or do you see this as rather hopeless?

I (personally) generally do not think that trying to redefine meaning of already popular and widely used tags (like `bottle=yes` / `bottle=no`) is likely going to be successful. The additional problem with `bottle=yes` is that not only it was not clearly defined, but also that some contexts it has well defined, but completely different meaning (e.g. for `fountain=bottle_refill`, it indicates instead whether _"empty bottles are available for purchase"_ instead of _"water bottle can easily be filled"_), and that it is highly subjective (what does _"easy"_ mean in that definition?)  

If one cares greatly and is willing to invest a lot of time, it might have better result, though. It wound need research, contacting many users of the tag, starting a discussion about that (linking to all related issues, tickets, discussions, wiki talk pages) etc. and presenting all that data to even get the discussion started.

E.g. for https://wiki.openstreetmap.org/wiki/Key:camp I've manually contacted few dozen top users to get their feedback on what they meant actually there. (and I still haven't finished that compilation of answers almost a year later, and it has about 20x less uses than `bottle=yes`).

---

What would IMHO be **quite more likely to succeed** (and would be lot less work, although still not insignificant by any means) is starting [proposal process](https://wiki.openstreetmap.org/wiki/Proposal_process) (and linking it to all the places mentioned above) to suggesting **additional clearer values** (like e.g. `bottle=impossible`, `bottle=hard`, `bottle=easy`, `bottle=only`) - and providing picture examples with explanations why some picture fits and doesn't fit into some category.  As additional benefit it would provide even more details. So if you're willing to invest some time into that tag, that is the route I'd recommend.

While that still has some issues with subjectivity / [verifyability](https://wiki.openstreetmap.org/wiki/Verifiability), those would be greatly reduced with picture examples and more detailed descriptions what fits which value (see e.g. `smoothness=*`, `track_type=*` for examples of tags which managed to have useful function even if they are somewhat subjective) and via extended discussion on e.g. [forum tagging category](https://community.openstreetmap.org/c/general/tagging/70).
