### ISSUE TITLE
Add "chipseal" as road surface type

### ISSUE THREAD

**Issue by ravenfeld** [Helium314/StreetComplete#561]
The topic has been closed on the StreetComplete side, so I've asked for it to be reanalysed. 

https://github.com/streetcomplete/StreetComplete/issues/4265

But I think the answer, as so often, will be no.

Can I propose my PR here? 
Or would you prefer to wait for a negative answer before coming back here?

**Comment by mnalis** [comment]
I would think you should at least  wait for at least a week or so for an possible acceptance there, especially since you already asked there. I've tried to add some more recent data and pros/cons and possible alternatives in that linked SC thread.

**Comment by ravenfeld** [comment]
I didn't know how responsive SC was. And it's more for an opinion of how it works. 
I've read your comments and they've almost convinced me that it shouldn't be on SC. In France I have the impression that people know the difference, but maybe not elsewhere, so maybe it's better that it's not on SC.

**Comment by mcliquid** [comment]
From my point of view, the change could already be integrated into SCEE. There are also some roads with chipseal in my rural area. If SC accepts it, the changes can be transferred quite easily.

**Comment by Helium314** [comment]
While I don't think a separate chipseal surface would be a useful addition, it would still be acceptable to have it as a choice for surface.
When adding, make sure you consider special treatment of existing chipseal tagging (I think there is some, if it wasn't removed meanwhile).

**Comment by ravenfeld** [comment]
> While I don't think a separate chipseal surface would be a useful addition, it would still be acceptable to have it as a choice for surface. When adding, make sure you consider special treatment of existing chipseal tagging (I think there is some, if it wasn't removed meanwhile).

I didn't understand what you meant by "When adding, make sure you consider special treatment of existing chipseal tagging (I think there is some, if it wasn't removed meanwhile)."

**Comment by mcliquid** [comment]
If it helps, here is already the image in all sizes:
[android-export.zip](https://github.com/user-attachments/files/16256196/android-export.zip)

**Comment by Helium314** [comment]
> I didn't understand what you meant by "When adding, make sure you consider special treatment of existing chipseal tagging (I think there is some, if it wasn't removed meanwhile)."

Possibly chipseal has some special treatment comparend to a "valid" SC surface, which might need to be adjusted.

**Comment by mcliquid** [comment]
I'm not sure if I'm interpreting correctly what you're trying to point out, but as far as I know there's only a dispute that chipseal should not be assigned by armchair mapping using only the aerial image, because according to some mappers the maximum you can correctly recognize is `paved`, but not whether it's `asphalt`, `concrete` or `chipseal`.
However, as SCEE is mapped on site, I still consider `chipseal` to be acceptable. What is known for sure is that chipseal is so little used that it is only the 37th most common value.

**Comment by Helium314** [comment]
I checked, and chipseal is treated as synonym of asphalt. This needs to be changed.

**Comment by mnalis** [comment]
> I checked, and chipseal is treated as synonym of asphalt. This needs to be changed.

You're talking about [SCEE codebase](https://github.com/Helium314/SCEE/blob/eb7855fc5a69160dbb9e4f6789efd82ffca8e823/app/src/main/java/de/westnordost/streetcomplete/osm/surface/Surface.kt#L40) here (for those _"checked is synonym"_ & _"needs to be changed"_), right? 
Not the [wiki](https://wiki.openstreetmap.org/wiki/Tag:surface%3Dchipseal) or something else?

**Comment by Helium314** [comment]
Yes. Though the comment does not matter

**Comment by mcliquid** [comment]
Last week I had the unique opportunity to find a road that had just been renewed with ‘chipseal’. I took some photos that show both the old condition, where the black tar (tarmac/bitumen) is clearly visible through the small and fine gravel, and the brand new, fresh and still loose area, where only the small and fine gravels are visible. I've uploaded a lot of pictures into this wikimedia category: https://commons.wikimedia.org/wiki/Category:Chipseal_pavements

**Comment by mnalis** [comment]
> Can I propose my PR here?

@ravenfeld With extra pictures, I think everything needed is ready, so you can proceed with PR for `surface=chipseal` (if you're still interested, of course)

**Comment by ravenfeld** [comment]
Which one do you want me to display?
The rest of the code is already operational on my repo so it's quick to propose it as normal unless compose has also caused the quest to work.

**Comment by mnalis** [comment]
Well I don't have `chipseal` around here so I cannot claim which is most representative, but many (especially on small screen) might look like `fine_gravel` instead, so are not good illustrations IMHO...

That being said, I'd probably choose [this one](https://commons.wikimedia.org/wiki/File:Road_surface_%22chipseal%22,_Bergerm%C3%BChlstra%C3%9Fe_in_Memmingen,_Germany_1.jpg)   (or alternatively [this](https://commons.wikimedia.org/wiki/File:Road_surface_%22chipseal%22,_Bergerm%C3%BChlstra%C3%9Fe_in_Memmingen,_Germany_4.jpg))

**Comment by mcliquid** [comment]
I would agree with the selection. The first picture clearly shows the mixture of tar/bitumen and fine chippings/gravel.
[chipseal.zip](https://github.com/user-attachments/files/16445464/chipseal.zip)

**Comment by mnalis** [comment]
@mcliquid looking at the smaller scale version you've prepared; I think maybe it would be better (instead of scaling whole original picture to `mdpi`->`xxdpi` scales), to instead cut from a center of the original picture and use that for generating pictures? 
That should probably make details somewhat bigger & more visible IMHO.

**Comment by mcliquid** [comment]
@mnalis If you think so, here are the new pictures - the section in the center has always been cropped to fit the new resolution.
[chipseal_centered.zip](https://github.com/user-attachments/files/16454065/chipseal_centered.zip)

Perhaps I am able to point out once that we are in the Expert Edition here and it can be assumed that users should know what value they are setting independent of the picture. And incidentally, there will not be a suitable translation of "Chipseal" for every language I guess. At least I am not aware of any in German. [Rollsplitt](https://de.wikipedia.org/wiki/Rollsplitt) seems to be the best translation but I would not be happy with that tbh because "Rollsplitt" is more or less "fine gravel" (without any bitumen).

**Comment by mnalis** [comment]
> the section in the center has always been cropped to fit the new resolution.

oh, ok then, I missed that

> we are in the Expert Edition here and it can be assumed that users should know what value they are setting independent of the picture. 

true, it was only minor idea improvement anyway

**Comment by mcliquid** [comment]
> oh, ok then, I missed that

I was only referring to the latest ZIP file, not the first version!
