### ISSUE TITLE
Quest Trail Visibilitity on private path

### ISSUE THREAD

**Issue by ravenfeld** [Helium314/StreetComplete#570]
While carrying out quests for sac_scale and trail visibility I realised that I was being asked for information on private paths.

Maybe add this for everyone who plays this quest?
```
      and access !~ no|private
      and foot !~ no|private
```

**Comment by mcliquid** [comment]
Yes, that should be a good idea, as one should assume that if you are permitted or have private access, you won't be able to get there. Super experts can still remove the filter themselves in the quest settings.

**Comment by mnalis** [comment]
Generally the idea might seem OK @ravenfeld  but I'm afraid such implementation is much too simple (unless I'm misreading it)

For example, there exist tag combinations like:
- `access=no` + `foot=yes`
- `access=private` + `foot=permissive`
- `foot=no` + `bicycle=designated` [^1]

etc. which should **all indicate it is OK for OSM mapper to legally be there and do the mapping**

Yet such simple filter would seem to skip all of them? 

While such oversimplification perhaps might be acceptable loss/gain ratio for vanilla StreetComplete, it doesn't feel as a good fit  SCEE-specific quests, IMHO, as its users should be quite familiar with _"don't enter private property"_ and other OSM mapping rules and often want to map all things they are allowed to, **instead of too simple filter incorrectly hiding  more than a third[^2] of such tag combinations**. 

Yes, in SCEE mappers can manually override quest selectors, but IMHO we still should tailor SCEE-specific Quests towards average SCEE user. Majority of which I think would definitely like to see paths tagged with `access=no` + `foot=yes` (and similar...)
 

---

Possible solutions:

- make a much more complex filter - i.e. one that would show the quest if there exist **any** [access tag](https://wiki.openstreetmap.org/wiki/Key:access) allows access (that is, has value different from `no|private`) as basically  SCEE mapper might use any mode of transport (e.g. `access=no` + `snowmobile=yes` is just fine). It would make sense to put it in a separate string/function so it can be used from other SCEE quests too.
- just don't bother excluding private paths for SCEE-only Quests.

[^1]: yeah, some folks do map from bicycles. I personally would recommend you always stop+map if you do that (unless you don't mind some self-inflicted damage occasionally :smiling_face_with_tear:) .  Some others map from busses, trains, as passengers in a car etc. too, but that is not applicable for those two specific quests (but might apply to other Quests) 
[^2]: I have not done detailed analyses of the tag usage, but just quickly guesstimated by looking at taginfo for [access=no combinations](https://taginfo.openstreetmap.org/tags/access=no#combinations), of which more than 35% _"no"_ values  were overridden by more specific access tags (like `foot=yes`, `bicycle=designated` etc).

**Comment by ravenfeld** [comment]
You're absolutely right, I got the code from  `AddCycleway`
and I noticed in my tests that my paths had no combination. So I'm going to fix that.
Thank you very much

**Comment by ravenfeld** [comment]
@mnalis 

I'll test your cases tomorrow, but it seems to me that's what you want?

`( access !~ no|private or foot ~ yes|permissive|designated or bicycle ~ yes|permissive|designated)`

I didn't understand snowmobile. Do you want me to take care of it? We're talking about hiking trails. Maybe let his people amend the application if that's the case no?

**Comment by Helium314** [comment]
> `( access !~ no|private or foot ~ yes|permissive|designated or bicycle ~ yes|permissive|designated)`

This looks like a reasonable (default) restriction to me.

**Comment by mnalis** [comment]
>     ( access !~ no|private or foot ~ yes|permissive|designated or bicycle ~ yes|permissive|designated)
> This looks like a reasonable (default) restriction to me.

It would work for me personally, but I guess that's because I'm always either on foot or on bicycle while mapping paths. But as you say, this is SCEE, so sub-optimal default is not a _huge_ deal, as any mapper can change it to their own preferences. 

We could go with that and extend it later if people complain... 

> I didn't understand snowmobile. Do you want me to take care of it? We're talking about hiking trails

Well, we are mostly talking about [highway=path](https://wiki.openstreetmap.org/wiki/Tag:highway=path), which _includes_ hiking trails, yes, but also includes many other things. 
One of which is mentioned [snowmobile](https://wiki.openstreetmap.org/wiki/Key:snowmobile) paths. I can't tell you much about them, as they don't really exist over here (Croatia is more well known for its sunny beaches, than its snow), but closer to the North pole snowmobiles are a thing (and I guess trail visibility on them might be as useful as it might be hiking trails and  bicycle paths)
