### ISSUE TITLE
Wi-Fi password quest

### ISSUE THREAD

**Issue by vfosnar** [Helium314/StreetComplete#603]
### General
Note: This quest has been rejected by SC: https://github.com/streetcomplete/StreetComplete/issues/5805

I can implement the quest myself if it gets a pass.

Affected tag(s) to be modified/added: [internet_access:password](https://wiki.openstreetmap.org/wiki/Tag:internet_access%3Dwlan)
Question asked: **What is the Wi-Fi password here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give should have an equivalent tagging (SCEE quests may not be answerable in all cases, but please keep this rare)
- [x] 🐿️ A survey is necessary (may require knowledge of the subject, though easy answering for everyone is preferred)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

```
internet_access=wlan and
internet_access:fee!=yes and
!internet_access:password
```

**Metadata needed:** 

**Proposed UI:**

- text input -> `internet_access:password:{value}`
- Uh... There is no password -> `internet_access:password:no`
- Uh... The Wi-Fi is protected but not using password -> `internet_access:password:yes`

**Comment by jonpsp** [comment]
I would think this could go out of date quickly - my local library (before it closed permanently for lack of funding) changed its WiFi password weekly.

**Comment by vfosnar** [comment]
Probably depends on location, I don't know a single place here in Czechia that ever changed their password except when they went out of business :D

I guess `internet_access:password:yes` should be used in such case too, atl for know when there is no standard tag for this

**Comment by vfosnar** [comment]
I don't see a problem with mapping such data as literally noone will go to a restaurant just for free wi-fi access.

I don't see it as a privacy issue as the password is literally given to anyone who buys something at the place. That's like mapping private roads, noone from the outside cares but it saves you and others time.

I proposed the following tags in my local community and waiting for responses, will update this thread later:
- internet_access:password=changes - password is periodically being changed
- internet_access:password=unique - password is different for each customer

**Comment by HolgerJeromin** [comment]
> I don't see it as a privacy issue as the password is literally given to anyone who buys something at the place.

But after adding this information to osm being a customer is not needed anymore.
Even more problematic for hotels where the password is written in the room but works at the whole hotel area.

IMO the owner of a property should be able to decide who gets access. Paint it at the wall or giving it only vip guests. His choice

**Comment by vfosnar** [comment]
> after adding this information to osm being a customer is not needed anymore

If I'd want to camp next to a restaurant/hotel/whatever and misuse their wi-fi I'd have to be a one time customer anyway to use it forever afterwards. Most restaurants don't have ppl standing around misusing their wi-fi and most hotels use per-customer credentials which shouldnt be uploaded to OSM.

> or giving it only vip guests

The idea behind this quest is to map wi-fi for usual customers only for convenience, hence why `internet_access:fee!=yes`.

> His choice

fair point, there should be a value representing that the owner doesn't want this info to be available on OSM, wheter the quests gets accepted or not.

something like internet_access:password=private

**Comment by mnalis** [comment]
On Sat, Aug 17, 2024 at 03:06:59PM -0700, Vojtěch Fošnár wrote:
> > after adding this information to osm being a customer is not needed anymore
> 
> If I'd want to camp next to a restaurant/hotel/whatever and misuse their wi-fi I'd have to be a one time customer anyway to use it forever afterwards. 

"I'd have to be a one time customer anyway" part is only correct if nobody ever shares the password.
If password is publicized (like on OSM), then it become "only one person ever would have to be customer, and everybody gets free wifi forever after", which is obviously bad deal for the owner who intened this wifi for their customers only (i.e. vast majority, if not all, of cafe owners).

> Most restaurants don't have ppl standing around misusing their wi-fi

I'd wager that this is only because their passwords are not publicly posted, and because they periodically change the password 
(to deter any attempts at sharing/publicising passwords, and to prune old customers).

If they didn't care if non-customers were using their wifi, they wouldn't go through the trouble to change it, EVER.
In fact, they would probably never require the password in the first place.

> > His choice
> 
> fair point, there should be a value representing that the owner doesn't want this info to be available on OSM, wheter the quests gets accepted or not.
> 
> something like internet_access:password=private

Then it is practically always (expect in few rare occasions) "internet_access:password=private".

You are aware that WiFi network can be "open", i.e. without any password, right? 

If the wifi owner WANTED *ANYONE* to be able to access it, they simply wouldn't put a password on it, and thus make it much EASIER for people to access it.
The very act of putting password means that they want to RESTRICT access to it.

Cafe etc. owners put password on WiFi so only their customers can access it. 
I.e. there is implicit trade there - you'll get free wifi as incentive to buy something here.
If you don't buy, we don't want to give you free wifi, but we want to reserve it for our customers only.

It is the same incentive as when there are situations when they offer "on your first order tonight, you get two drinks for the price of one!" (i.e. second drink is gratis).
It does not mean "drinks are gratis here, come in and drink as much as you want for no money", but it is incentive to become (paying!) customer. 
And offered only because (statistically) majority of customers will order more than that first drink once they are seated.

Anyway, I've opened https://community.openstreetmap.org/t/opinions-on-internet-access-password/117581
for discussion on the subject.

-- 
Opinions above are GNU-copylefted.

**Comment by Atrate** [comment]
I'd say that if this ever got implemented, it should have a pretty restrictive filter, e.g. "show for cafes, restaurants, but not hotels, bnbs". As to what is actually included in that filter would require further dicsussion.

**Comment by Helium314** [comment]
I wouldn't see a key with ~1000 uses to be _established...
Anyway since the vote result in https://community.openstreetmap.org/t/opinions-on-internet-access-password/117581/2 is very clear I would not want this quest in SCEE, sorry.
