### ISSUE TITLE
I think all quests solved in SCEE are increasing the quest counter stats

### ISSUE THREAD

**Issue by pkoby** [Helium314/StreetComplete#645]
I'm not 100% sure on this, but I think that every quest answered in SCEE is bumping up the quest counter, and the number is matching in normal SC. I am not sure if it's based on changeset tags, but I was under the impression that at least some quests (the ones not in normal SC) wouldn't count towards the stats. I've tried solving only SCEE-specific quests, and the number still goes up in both apps. If this is not a bug, I'm fine with that, but I wasn't sure if this was intended.

**How to Reproduce**
Solve a quest.

**Expected Behavior**
Some quests aren't supposed to increase the stat counter. I think it used to be that nothing in SCEE would count, but I'm not sure if that's changed.

**Does it happen in normal StreetComplete?**
n/a

**Versions affected**
V59.0-alpha2

**Comment by mnalis** [comment]
> I've tried solving only SCEE-specific quests, and the number still goes up in both apps. 
> If this is not a bug, I'm fine with that, but I wasn't sure if this was intended.

It seems to be intended, see https://github.com/Helium314/SCEE/issues/370#issuecomment-1555234998 and linked comments

**Comment by pkoby** [comment]
Okay cool. I don't know if I misunderstand those comments, but I don't see anything that clarifies whether SCEE-specific quests are counted. In my testing, it seems that they are. I'm happy that at least most quests are bumping up the number regardless of which build I use.

**Comment by mnalis** [comment]
see part:
> So having statistics without claiming to be StreetComplete can be done, even including SCEE-only quests (see https://github.com/streetcomplete/StreetComplete/issues/1894).

(and also details in that linked upstream issue 1894 where StreetComplete statistics gathering process is explained, as well later comments in SCEE https://github.com/Helium314/SCEE/issues/370#issuecomment-1554287568 when upstream confirms that such behaviour [statistics from SCEE quests being counted in SC also] is fine with them)

**Comment by meiphoo7-Mae** [comment]
It goes even further than this. I use both apps and there's even a difference in achievements level in the profile. SCEE counts additional achievements and therefore there's a difference. In my case the difference is 1 achievement. Probably the difference can be higher but a number of quests are not asked in my country...

But honestly: these statistics reported by SC and SCEE are just eye candy. The real statistics are maintained in your OSM profile and if you compare the OSM statistics and those of SC or SCEE you'll eventually notice that the number of solved quests counted by SC/SCEE can be more than double as high as those counted by OSM.
Also the achievement "balls" in the star tab in SC/SCEE are just eye candy without real meaning but fortunately those have the advantage of being an easy access to the relevant quest documentation.

**Comment by mnalis** [comment]
> But honestly: these statistics reported by SC and SCEE are just eye candy

Sure. Any statistics of that type are; they are irrelevant for OSM data, and useful only insomuch they entice users to contribute even more.  So, gamification factor, yes (and being eye candy helps there a lot!)

> Also the achievement "balls" in the star tab in SC/SCEE are just eye candy without real meaning

Well, I'd disagree with _"without real meaning"_. You get a "ball" if you solved the quest of that type, and the size of the ball (relative to other balls) is how many quests of that type have you solved relative to the other types. So there is a meaning... So yeah, It is not hard number, but was not supposed to be. Compared to hard numbers, they are lovely looking and very fun, and loveliness and fun is big part of SC (and by extension, SCEE) success. 

When my wife introduces OSM to others, those SC balls are among first things she shows and people show interest. If she would instead recite numbers of modified and added OSM objects and percentage of tags updated per area, I very much doubt it would raise as much interest in most of them :smile:  

IOW, just because balls are not what bean counters would prefer, it does not mean they are not useful.

**Comment by mnalis** [comment]
Anyway, as original question has been answered, unless someone objects, I'll close this (in order to reduce workload).

**Comment by Helium314** [comment]
Thanks for explaining @mnalis!
So from my point of view: I don't care whether any/all/some quests count towards SC statistics, SC authoer is ok with this, and users wanted statistics (and adding to SC statistics resulted in a _considerable_ increase in SCEE use)
